// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yggdrasil.Quotation.Infrastructure.Persistence;

#nullable disable

namespace Yggdrasil.Quotation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124181419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.AmortizationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interest")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestTax")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestTaxBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrincipalBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuoteEngineId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_AmortizationSchedules_DueDate");

                    b.HasIndex("PeriodNumber")
                        .HasDatabaseName("IX_AmortizationSchedules_PeriodNumber");

                    b.HasIndex("QuoteEngineId")
                        .HasDatabaseName("IX_AmortizationSchedules_QuoteEngineId");

                    b.HasIndex("QuoteEngineId", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_AmortizationSchedules_QuoteEngineId_PeriodNumber");

                    b.ToTable("AmortizationSchedules", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.InterestRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualPercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_InterestRates_EffectiveDate");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("IX_InterestRates_ExpirationDate");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_InterestRates_IsActive");

                    b.HasIndex("RateName")
                        .HasDatabaseName("IX_InterestRates_RateName");

                    b.HasIndex("IsActive", "EffectiveDate", "ExpirationDate")
                        .HasDatabaseName("IX_InterestRates_Active_DateRange");

                    b.ToTable("InterestRates", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.PaymentFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodsPerYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentFrequencies_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PaymentFrequencies_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_PaymentFrequencies_Name");

                    b.HasIndex("IsActive", "DaysInterval")
                        .HasDatabaseName("IX_PaymentFrequencies_Active_DaysInterval");

                    b.ToTable("PaymentFrequencies", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.PaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPayments")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentTerms_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PaymentTerms_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_PaymentTerms_Name");

                    b.HasIndex("NumberOfPayments")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentTerms_NumberOfPayments");

                    b.ToTable("PaymentTerms", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaxRateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_Plans_EndDate");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Plans_Name");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Plans_StartDate");

                    b.HasIndex("TaxRateId");

                    b.HasIndex("MinAge", "MaxAge")
                        .HasDatabaseName("IX_Plans_AgeRange");

                    b.HasIndex("MinAmount", "MaxAmount")
                        .HasDatabaseName("IX_Plans_AmountRange");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Plans_DateRange");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.PlanPaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestRateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentTermId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterestRateId")
                        .HasDatabaseName("IX_PlanPaymentTerms_InterestRateId");

                    b.HasIndex("Order")
                        .HasDatabaseName("IX_PlanPaymentTerms_Order");

                    b.HasIndex("PaymentTermId")
                        .HasDatabaseName("IX_PlanPaymentTerms_PaymentTermId");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_PlanPaymentTerms_PlanId");

                    b.HasIndex("PlanId", "Order")
                        .HasDatabaseName("IX_PlanPaymentTerms_PlanId_Order");

                    b.HasIndex("PlanId", "PaymentTermId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanPaymentTerms_PlanId_PaymentTermId");

                    b.ToTable("PlanPaymentTerms", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.QuoteEngine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InsurancePercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InsuranceRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Term")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Amount")
                        .HasDatabaseName("IX_QuoteEngines_Amount");

                    b.HasIndex("FrequencyId")
                        .HasDatabaseName("IX_QuoteEngines_FrequencyId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_QuoteEngines_Status");

                    b.HasIndex("Term")
                        .HasDatabaseName("IX_QuoteEngines_Term");

                    b.HasIndex("Status", "FrequencyId", "Term")
                        .HasDatabaseName("IX_QuoteEngines_Status_Frequency_Term");

                    b.ToTable("QuoteEngines", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(6, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_TaxRates_Code");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_TaxRates_EffectiveDate");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("IX_TaxRates_ExpirationDate")
                        .HasFilter("[ExpirationDate] IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TaxRates_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_TaxRates_Name");

                    b.HasIndex("Percentage")
                        .HasDatabaseName("IX_TaxRates_Percentage");

                    b.HasIndex("IsActive", "EffectiveDate", "ExpirationDate")
                        .HasDatabaseName("IX_TaxRates_Active_DateRange");

                    b.ToTable("TaxRates", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.AmortizationSchedule", b =>
                {
                    b.HasOne("Yggdrasil.Quotation.Domain.Entities.QuoteEngine", "QuoteEngine")
                        .WithMany("AmortizationSchedules")
                        .HasForeignKey("QuoteEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteEngine");
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.Plan", b =>
                {
                    b.HasOne("Yggdrasil.Quotation.Domain.Entities.TaxRate", null)
                        .WithMany("Plans")
                        .HasForeignKey("TaxRateId");
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.PlanPaymentTerm", b =>
                {
                    b.HasOne("Yggdrasil.Quotation.Domain.Entities.InterestRate", "InterestRate")
                        .WithMany("PlanPaymentTerms")
                        .HasForeignKey("InterestRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yggdrasil.Quotation.Domain.Entities.PaymentTerm", "PaymentTerm")
                        .WithMany()
                        .HasForeignKey("PaymentTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yggdrasil.Quotation.Domain.Entities.Plan", "QuotationPlan")
                        .WithMany("PlanTerms")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterestRate");

                    b.Navigation("PaymentTerm");

                    b.Navigation("QuotationPlan");
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.InterestRate", b =>
                {
                    b.Navigation("PlanPaymentTerms");
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanTerms");
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.QuoteEngine", b =>
                {
                    b.Navigation("AmortizationSchedules");
                });

            modelBuilder.Entity("Yggdrasil.Quotation.Domain.Entities.TaxRate", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
